project:
  type: website
  output-dir: docs

website:
  title: "Gaming Tuberz"
  site-url: 'https://www.gamingtuberz.com'
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  page-footer: "Copyright © 2023 Indian Gaming"
  navbar:
    search: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


