project:
  type: website
  output-dir: docs

website:
  title: "Testing Blog"
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  body-footer: |
    Copyright © 2023 Indian Gaming
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


