project:
  type: website
  output-dir: docs

website:
  favicon: website_icon.svg
  title: "Gaming Tuberz"
  site-url: "https://www.gamingtuberz.com"
  open-graph: true
  cookie-consent:
    type: express
    style: headline
    palette: dark
  page-footer: "Copyright © 2023 Gaming Tuberz"
  navbar:
    search: true
    right:
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


